roles:
- [mon.a, mgr.x, osd.0, osd.1, osd.2, osd.3]
- [mon.b, osd.4, osd.5, osd.6, osd.7]
- [mon.c, osd.8, osd.9, osd.10, osd.11]
- [client.0]

tasks:
- install:
    extra_system_packages:
      - fio
- ceph:
- exec:
    client.0:
      - sleep 24h
